export const FETCH_USERS_POSTS_REQUEST = "FETCH_USERS_POSTS_REQUEST";
export const FETCH_USERS_POSTS_SUCCESS = "FETCH_USERS_POSTS_SUCCESS";
export const FETCH_USERS_POSTS_FAILURE = "FETCH_USERS_POSTS_FAILURE";
