export const FETCH_SEARCHED_USERS_REQUEST = "FETCH_SEARCHED_USERS_REQUEST";
export const FETCH_SEARCHED_USERS_SUCCESS = "FETCH_SEARCHED_USERS_SUCCESS";
export const FETCH_SEARCHED_USERS_FAILURE = "FETCH_SEARCHED_USERS_FAILURE";
